// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjdihppgtzxzexisihbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqZGlocHBndHp4emV4aXNpaGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzYyNjQsImV4cCI6MjA2NTA1MjI2NH0.PSDvhumQhGe6wrcLzs0RSkCFo7D5xVnAv7mnZI8yJJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);